// ════════════════════════════════════════════════════════════════
//  MIRROR of mobile lib/trainingPrograms.js
//  Source: HITTRACK-App-main/lib/trainingPrograms.js
//
//  ⚠ DO NOT EDIT THIS FILE INDEPENDENTLY.
//  When the mobile teammate changes the source, sync this copy.
//  Web and mobile must agree on movement definitions, program
//  templates, rep counts, and stance resolution — otherwise a
//  member who sets up on one platform will see different training
//  on the other.
// ════════════════════════════════════════════════════════════════
//
//  HITTRACK — Training Programs Library
//
//  Defines every movement, program templates per goal, count rules,
//  and a generator function that produces a user's full training
//  program from their profile (stance + goal + experience).
// ════════════════════════════════════════════════════════════════

// ── COUNTS ───────────────────────────────────────────────────────
const COUNTS = {
  standard: { beginner: 50,  intermediate: 100, advanced: 150 },
  doubled:  { beginner: 100, intermediate: 150, advanced: 200 },
  strength: { beginner: 20,  intermediate: 40,  advanced: 60  },
  strengthDoubled: { beginner: 40, intermediate: 80, advanced: 120 },
  defense:  { beginner: 20,  intermediate: 40,  advanced: 60  },
  defenseDoubled: { beginner: 40, intermediate: 80, advanced: 120 },
}

// ── MOVEMENT LIBRARY ─────────────────────────────────────────────
// Each movement has:
//   id, type, icon, baseCountKey, detection (for MoveNet later),
//   description, whyUse, howTo (array of steps), cameraDistance
//
// Punch names are resolved at generation time based on stance.
// ─────────────────────────────────────────────────────────────────
export const MOVEMENT_LIBRARY = {

  // ── PUNCHES ──────────────────────────────────────────────────
  jab: {
    id: 'jab',
    type: 'punch',
    hand: 'lead',               // resolved to left/right based on stance
    icon: '🥊',
    baseCountKey: 'standard',
    color: '#E63946',
    detection: { method: 'wrist_extension', primary: 'lead_wrist', threshold: 0.65 },
    description: 'The jab is your most important weapon in boxing. It\'s a quick, straight punch thrown with your lead hand — used to measure distance, control range, disrupt rhythm, and set up power combinations.',
    whyUse: 'The jab is the foundation of boxing. A sharp jab controls distance, keeps your opponent on the back foot, and opens every major combination in the sport.',
    howTo: [
      'Start in your boxing stance with your guard up — both fists near your cheekbones.',
      'Extend your lead hand straight forward, rotating your fist so the palm faces down at the point of impact.',
      'Snap your arm back immediately to your guard position after each jab.',
      'Keep your rear hand glued to your chin throughout the entire movement.',
      'Push off your lead foot slightly to add reach — keep your weight balanced.',
    ],
    cameraDistance: 'Stand approximately 1.5–2 meters (5–6 feet) from your phone, placed at chest height. Your full body from head to hip should be visible on screen.',
  },

  cross: {
    id: 'cross',
    type: 'punch',
    hand: 'rear',
    icon: '🥊',
    baseCountKey: 'standard',
    color: '#E63946',
    detection: { method: 'wrist_extension', primary: 'rear_wrist', threshold: 0.65 },
    description: 'The cross is a powerful straight punch thrown with your rear hand. It travels a longer distance than the jab, generating more force from hip and shoulder rotation.',
    whyUse: 'The cross is your primary power punch. Combined with the jab (the classic 1-2 combination), it is the most fundamental offensive sequence in all of boxing.',
    howTo: [
      'From your boxing stance, begin by pivoting on the ball of your rear foot.',
      'Rotate your rear hip and shoulder forward as you extend your rear hand straight toward the target.',
      'Rotate your fist so the palm faces down at the point of impact.',
      'Keep your lead hand protecting your chin as your rear hand extends.',
      'Snap back to your full guard position immediately after the punch lands.',
    ],
    cameraDistance: 'Stand approximately 1.5–2 meters (5–6 feet) from your phone, placed at chest height. Make sure your full upper body and both arms are visible when extended.',
  },

  lead_hook: {
    id: 'lead_hook',
    type: 'punch',
    hand: 'lead',
    icon: '🥊',
    baseCountKey: 'standard',
    color: '#F5C842',
    detection: { method: 'lateral_arc', primary: 'lead_wrist', threshold: 0.6 },
    description: 'The lead hook is a power punch thrown in a horizontal arc with your lead hand. It attacks from an angle, often bypassing the opponent\'s straight guard to land on the side of the head or jaw.',
    whyUse: 'The hook targets the side of the head and is one of boxing\'s most common knockout punches. It is most effective after a jab-cross combination when your opponent\'s guard is focused straight ahead.',
    howTo: [
      'From your stance, rotate your lead hip and shoulder toward your target.',
      'Keep your elbow bent at approximately 90 degrees throughout the punch.',
      'Swing your lead fist in a horizontal arc across your body.',
      'Pivot on your lead foot as you throw — your heel should rise slightly.',
      'Your knuckles should be facing away from you at the moment of impact.',
      'Return immediately to your full guard after the hook.',
    ],
    cameraDistance: 'Stand approximately 1.5–2 meters from your phone at chest height. Your body from head to hip must be fully visible, especially your lead arm arc.',
  },

  rear_hook: {
    id: 'rear_hook',
    type: 'punch',
    hand: 'rear',
    icon: '🥊',
    baseCountKey: 'standard',
    color: '#F5C842',
    detection: { method: 'lateral_arc', primary: 'rear_wrist', threshold: 0.6 },
    description: 'The rear hook is a powerful punch thrown with the rear hand in a horizontal arc. It generates tremendous force from the hip and shoulder rotation of the rear side.',
    whyUse: 'The rear hook is devastating when used after your opponent focuses on defending straight punches. It comes from an unexpected angle with maximum hip rotation behind it.',
    howTo: [
      'From your stance, pivot on your rear foot while rotating your rear hip and shoulder forward.',
      'Keep your rear elbow bent at 90 degrees as you swing your rear fist in a horizontal arc.',
      'Keep your lead hand protecting your chin throughout the punch.',
      'Your body weight should shift forward and toward your lead side as you throw.',
      'Snap back to guard immediately after the punch.',
    ],
    cameraDistance: 'Stand approximately 1.5–2 meters from your phone at chest height, ensuring your full upper body and arm arc are visible.',
  },

  lead_uppercut: {
    id: 'lead_uppercut',
    type: 'punch',
    hand: 'lead',
    icon: '🥊',
    baseCountKey: 'standard',
    color: '#4ade80',
    detection: { method: 'upward_arc', primary: 'lead_wrist', threshold: 0.6 },
    description: 'The lead uppercut is a compact upward punch thrown with the lead hand, targeting the chin or solar plexus. It is most effective at close range when your opponent\'s guard is high.',
    whyUse: 'The uppercut travels underneath the opponent\'s guard and strikes upward on the chin — one of the most effective knockdown punches. It is a key weapon when fighting on the inside.',
    howTo: [
      'Drop your lead shoulder slightly and bend your lead knee to load the punch.',
      'Drive upward with your legs as you rotate your lead hip forward.',
      'Swing your lead fist upward in a palm-up, scooping motion.',
      'Keep your elbow bent and close to your body — this is a compact punch.',
      'Keep your rear hand protecting your chin throughout.',
      'Return to guard immediately after the punch.',
    ],
    cameraDistance: 'Stand approximately 1.5 meters from your phone at chest height. The upward wrist motion must be clearly visible — ensure nothing blocks the lower portion of your body.',
  },

  rear_uppercut: {
    id: 'rear_uppercut',
    type: 'punch',
    hand: 'rear',
    icon: '🥊',
    baseCountKey: 'standard',
    color: '#4ade80',
    detection: { method: 'upward_arc', primary: 'rear_wrist', threshold: 0.6 },
    description: 'The rear uppercut is a powerful upward punch thrown with the rear hand, combining full hip rotation with an explosive upward driving motion.',
    whyUse: 'The rear uppercut is one of the most powerful punches in boxing at close range. The combination of hip rotation and upward drive generates tremendous force directed at the chin.',
    howTo: [
      'Drop your rear shoulder and bend your rear knee slightly to load the punch.',
      'Drive upward explosively, rotating your rear hip fully forward.',
      'Swing your rear fist upward in a scooping motion, palm facing up.',
      'Keep the elbow bent and the motion compact — drive through with the whole body.',
      'Keep your lead hand up protecting your face throughout.',
      'Snap back to guard immediately.',
    ],
    cameraDistance: 'Stand approximately 1.5 meters from your phone at chest height. Ensure your full body from head to hip is visible with nothing blocking your lower body.',
  },

  // ── DEFENSE MOVEMENTS ─────────────────────────────────────────
  slip_right: {
    id: 'slip_right',
    type: 'defense',
    hand: null,
    icon: '🛡️',
    baseCountKey: 'defense',
    color: '#42a5f5',
    detection: { method: 'head_lateral', direction: 'right', threshold: 0.5 },
    description: 'The slip right is a defensive head movement where you shift your head to the right to avoid an incoming straight punch, while keeping your hands up protecting your face.',
    whyUse: 'Slipping takes your head off the centerline — the line where punches travel. Moving your head to the right takes you to the outside of your opponent\'s lead hand and positions you for a powerful counter-attack.',
    howTo: [
      'Start in your boxing stance with both hands up protecting your face.',
      'Quickly bend your right knee and rotate your upper body to the right.',
      'Your head should move to the outside of the imaginary incoming jab.',
      'Keep BOTH hands up near your temples throughout the slip.',
      'Do not lean forward or bend at the waist — the movement comes from bending the knee.',
      'Return to upright stance immediately and be ready to counter.',
    ],
    cameraDistance: 'Stand approximately 1.5–2 meters from your phone at chest or shoulder height. Your head and both arms must be clearly visible for the movement to be tracked.',
  },

  slip_left: {
    id: 'slip_left',
    type: 'defense',
    hand: null,
    icon: '🛡️',
    baseCountKey: 'defense',
    color: '#42a5f5',
    detection: { method: 'head_lateral', direction: 'left', threshold: 0.5 },
    description: 'The slip left is a defensive head movement where you shift your head to the left to avoid an incoming straight punch while maintaining your guard.',
    whyUse: 'Slipping to the left puts you on the inside — positioned for a powerful counter-punch with your rear hand. It is one of the best setups for landing a counter-cross or rear uppercut.',
    howTo: [
      'Start in your boxing stance with both hands up protecting your face.',
      'Quickly bend your left knee and rotate your upper body to the left.',
      'Your head moves to the inside of the imaginary incoming punch.',
      'Keep BOTH hands up near your temples throughout the entire slip.',
      'Do not lean forward or bend at the waist — move from the knee bend and rotation.',
      'Return to your upright stance immediately and prepare your counter.',
    ],
    cameraDistance: 'Stand approximately 1.5–2 meters from your phone at chest or shoulder height. Head and both arms must remain visible throughout.',
  },

  bob_and_weave: {
    id: 'bob_and_weave',
    type: 'defense',
    hand: null,
    icon: '🛡️',
    baseCountKey: 'defense',
    color: '#42a5f5',
    detection: { method: 'head_vertical_lateral', threshold: 0.5 },
    description: 'Bob and weave is a defensive technique where you bend your knees to duck under a punch and simultaneously shift your head to one side, emerging on the other side of the punch with your hands up.',
    whyUse: 'Bob and weave is one of boxing\'s most dynamic defensive skills. It takes you completely under and outside an incoming punch while positioning you to deliver devastating counter-punches from the inside.',
    howTo: [
      'Start in your boxing stance with both hands up protecting your face.',
      'Bend both knees simultaneously to lower your head below the imaginary punch.',
      'As you dip, shift your body weight to one side (e.g., shift left while dipping).',
      'Come back up on the opposite side of the imaginary punch (emerging right).',
      'Keep BOTH hands up near your face throughout the entire movement.',
      'The full movement is: bend knees → dip down → shift sideways → rise on the other side.',
      'Practice smoothly — it should feel like a U-shape movement with the head.',
    ],
    cameraDistance: 'Stand approximately 1.5–2 meters from your phone at chest height. Your full body from head to knee must be visible to track both the vertical dip and lateral shift.',
  },

  // ── STRENGTH EXERCISES ────────────────────────────────────────
  squat: {
    id: 'squat',
    type: 'strength',
    hand: null,
    icon: '💪',
    baseCountKey: 'strength',
    color: '#c084fc',
    detection: { method: 'hip_depth', threshold: 0.5 },
    description: 'The squat is a fundamental strength exercise that builds explosive leg power — the foundation of everything in boxing. Every powerful punch starts from the legs up.',
    whyUse: 'Strong legs generate the drive and rotation behind every punch. Squats develop the explosive power needed to push off the ground and transfer energy through your hips into your punches.',
    howTo: [
      'Stand with feet shoulder-width apart, toes pointed slightly outward.',
      'Keep your chest up and your back straight throughout.',
      'Lower your body by bending at the knees and pushing your hips back — like sitting into a chair.',
      'Go down until your thighs are parallel to the floor (or as low as comfortable).',
      'Drive back up through your heels to the standing position.',
      'Squeeze your glutes at the top of each rep.',
    ],
    cameraDistance: 'Stand approximately 1.5–2 meters from your phone. Place it at hip to chest height. Your full body from head to feet must be visible to track the hip depth.',
  },

  broad_jump: {
    id: 'broad_jump',
    type: 'strength',
    hand: null,
    icon: '💪',
    baseCountKey: 'strength',
    color: '#c084fc',
    detection: { method: 'jump_detection', threshold: 0.5 },
    description: 'The broad jump is an explosive plyometric exercise that develops the fast-twitch power needed for quick in-and-out footwork in boxing.',
    whyUse: 'Boxing requires explosive, fast-twitch leg movements — darting in to land a punch and immediately moving out of range. Broad jumps develop exactly this type of explosive power.',
    howTo: [
      'Stand with feet shoulder-width apart.',
      'Bend your knees and swing both arms back to load the jump.',
      'Explosively jump forward as far as possible, swinging your arms forward for momentum.',
      'Aim for maximum horizontal distance.',
      'Land softly on both feet simultaneously with your knees bent to absorb the impact.',
      'Stand up straight and return to the starting position for the next rep.',
    ],
    cameraDistance: 'Stand approximately 2 meters from your phone placed at hip height on a stable surface. Ensure there is at least 2 meters of clear space in front of you for the jump. Your full body must be visible.',
  },

  russian_twist: {
    id: 'russian_twist',
    type: 'strength',
    hand: null,
    icon: '💪',
    baseCountKey: 'strength',
    color: '#c084fc',
    detection: { method: 'torso_rotation', threshold: 0.5 },
    description: 'The Russian twist is a core exercise that builds rotational power — the exact same rotation that generates force in every punch you throw.',
    whyUse: 'Every single punch in boxing is powered by torso rotation. Russian twists specifically target the oblique muscles used to rotate the hips and shoulders, directly transferring to punch power.',
    howTo: [
      'Sit on the floor with your knees bent and feet flat on the floor (or raised for more difficulty).',
      'Lean back slightly at around 45 degrees, keeping your back straight — not rounded.',
      'Clasp both hands together in front of your chest.',
      'Rotate your upper body fully to the right, bringing your hands to hip level.',
      'Return to center, then rotate fully to the left.',
      'Right + left = one repetition. Keep the movement controlled and deliberate.',
    ],
    cameraDistance: 'Place your phone approximately 1.5 meters away at floor level or on a low surface. Your full upper body and both arms must be visible while you are seated.',
  },

  lunge: {
    id: 'lunge',
    type: 'strength',
    hand: null,
    icon: '💪',
    baseCountKey: 'strength',
    color: '#c084fc',
    detection: { method: 'single_knee_depth', threshold: 0.5 },
    description: 'The lunge is a single-leg strength and balance exercise that develops the stability and power needed when shifting weight between legs during boxing combinations.',
    whyUse: 'Boxing requires constant single-leg balance — stepping in to punch, pivoting, and moving laterally. Lunges build the unilateral strength and coordination needed for these movements.',
    howTo: [
      'Stand upright with feet together and hands by your sides or on your hips.',
      'Step one foot forward a comfortable stride length.',
      'Lower your back knee toward the floor, bending both knees to approximately 90 degrees.',
      'Keep your front knee directly above your front ankle — not caving inward.',
      'Keep your torso upright throughout — do not lean forward.',
      'Push back up through your front heel to the starting position.',
      'Alternate legs with each rep — right step + left step = two reps.',
    ],
    cameraDistance: 'Stand approximately 2 meters from your phone placed at hip to chest height. Your full body from head to feet must be visible to track both knee positions.',
  },
}

// ── PROGRAM TEMPLATES ─────────────────────────────────────────────
// Defines the ordered sequence of movements for each goal.
// countMultiplier: 'standard' or 'doubled'
// ─────────────────────────────────────────────────────────────────
export const PROGRAM_TEMPLATES = {
  'Lose Weight': {
    countMultiplier: 'doubled',
    sequence: [
      'jab', 'cross', 'lead_hook', 'rear_hook', 'lead_uppercut', 'rear_uppercut',
    ],
  },
  'Build Strength': {
    countMultiplier: 'standard',
    sequence: [
      'jab', 'squat', 'cross', 'broad_jump',
      'lead_hook', 'russian_twist', 'rear_hook', 'lunge',
      'lead_uppercut', 'rear_uppercut',
    ],
  },
  'Learn Boxing': {
    countMultiplier: 'standard',
    sequence: [
      'jab', 'cross', 'slip_right', 'slip_left',
      'lead_hook', 'rear_hook', 'bob_and_weave',
      'lead_uppercut', 'rear_uppercut',
    ],
  },
  'Compete': {
    countMultiplier: 'doubled',
    sequence: [
      'jab', 'squat', 'cross', 'broad_jump',
      'slip_right', 'russian_twist', 'slip_left', 'lunge',
      'lead_hook', 'rear_hook', 'bob_and_weave',
      'lead_uppercut', 'rear_uppercut',
    ],
  },
}

// ── STANCE LABELS ────────────────────────────────────────────────
const STANCE_MAP = {
  Orthodox: { lead: 'Left',  rear: 'Right', leadFull: 'Left Hand',  rearFull: 'Right Hand' },
  Southpaw: { lead: 'Right', rear: 'Left',  leadFull: 'Right Hand', rearFull: 'Left Hand'  },
}

// ── GET COUNTS ───────────────────────────────────────────────────
function getCounts(baseCountKey, multiplier) {
  if (baseCountKey === 'strength') {
    return multiplier === 'doubled' ? COUNTS.strengthDoubled : COUNTS.strength
  }
  if (baseCountKey === 'defense') {
    return multiplier === 'doubled' ? COUNTS.defenseDoubled : COUNTS.defense
  }
  // punch (standard)
  return multiplier === 'doubled' ? COUNTS.doubled : COUNTS.standard
}

// ── RESOLVE MOVEMENT NAME ────────────────────────────────────────
function resolveMovementName(movement, stanceInfo) {
  if (!movement.hand) return movement.id === 'bob_and_weave' ? 'Bob and Weave' : movement.id.split('_').map(w => w[0].toUpperCase() + w.slice(1)).join(' ')
  const handLabel = movement.hand === 'lead' ? stanceInfo.lead : stanceInfo.rear
  const base = movement.id
    .replace('lead_', '').replace('rear_', '')
    .split('_').map(w => w[0].toUpperCase() + w.slice(1)).join(' ')
  return `${handLabel} ${base}`
}

// ── MAIN GENERATOR ───────────────────────────────────────────────
// Call this when the user completes the program builder.
// Returns the full training program array to save to Firestore.
//
// @param {string} stance     - 'Orthodox' | 'Southpaw'
// @param {string} goal       - 'Lose Weight' | 'Build Strength' | 'Learn Boxing' | 'Compete'
// @param {string} experience - 'Beginner' | 'Intermediate' | 'Advanced'
// @returns {object}          - { trainings: [...], startingLevel, currentLevel, completedLevels }
// ─────────────────────────────────────────────────────────────────
export function generateTrainingProgram(stance, goal, experience) {
  const template    = PROGRAM_TEMPLATES[goal] || PROGRAM_TEMPLATES['Learn Boxing']
  const stanceInfo  = STANCE_MAP[stance]      || STANCE_MAP['Orthodox']
  const multiplier  = template.countMultiplier
  const startLevel  = (experience || 'Beginner').toLowerCase()

  const trainings = template.sequence.map((movId, index) => {
    const mov    = MOVEMENT_LIBRARY[movId]
    if (!mov) return null
    const counts = getCounts(mov.baseCountKey, multiplier)
    const name   = resolveMovementName(mov, stanceInfo)

    // For punches, resolve which keypoint to track based on stance
    let detection = { ...mov.detection }
    if (mov.hand === 'lead') {
      detection.trackedKeypoint = stanceInfo.lead === 'Left' ? 'left_wrist' : 'right_wrist'
    } else if (mov.hand === 'rear') {
      detection.trackedKeypoint = stanceInfo.rear === 'Left' ? 'left_wrist' : 'right_wrist'
    }

    return {
      id:          movId,
      order:       index,
      name,
      type:        mov.type,
      hand:        mov.hand,
      handLabel:   mov.hand ? (mov.hand === 'lead' ? stanceInfo.leadFull : stanceInfo.rearFull) : null,
      icon:        mov.icon,
      color:       mov.color,
      description: mov.description,
      whyUse:      mov.whyUse,
      howTo:       mov.howTo,
      cameraDistance: mov.cameraDistance,
      detection,
      // Count requirements per level
      requiredReps: {
        beginner:     counts.beginner,
        intermediate: counts.intermediate,
        advanced:     counts.advanced,
      },
      // Progress tracking
      unlocked:        index === 0,   // only first is unlocked at start
      completedLevels: [],             // ['beginner', 'intermediate', 'advanced']
      currentLevelReps: 0,            // reps done in current level session
    }
  }).filter(Boolean)

  return {
    goal,
    stance,
    experience,
    startingLevel:   startLevel,
    currentLevel:    startLevel,
    currentTrainingIndex: 0,
    levelStars:      startLevel === 'beginner' ? 1 : startLevel === 'intermediate' ? 2 : 3,
    completedLevels: [],
    trainings,
    generatedAt:     new Date().toISOString(),
  }
}

// ── HELPERS ──────────────────────────────────────────────────────

/** Get the current required reps for a training at a given level */
export function getRequiredReps(training, level) {
  return training.requiredReps?.[level] ?? training.requiredReps?.beginner ?? 50
}

/** Get star count for a level */
export function getLevelStars(level) {
  if (level === 'advanced')     return 3
  if (level === 'intermediate') return 2
  return 1
}

/** Get the next level */
export function getNextLevel(currentLevel) {
  if (currentLevel === 'beginner')     return 'intermediate'
  if (currentLevel === 'intermediate') return 'advanced'
  return null  // already at max
}

/** Check if all trainings in a level are complete */
export function isLevelComplete(trainings, level) {
  return trainings.every(t => t.completedLevels?.includes(level))
}

/** Get level display label */
export function getLevelLabel(level) {
  if (level === 'beginner')     return 'Beginner'
  if (level === 'intermediate') return 'Intermediate'
  if (level === 'advanced')     return 'Advanced'
  return 'Beginner'
}

/** Get type display label and color */
export function getTypeInfo(type) {
  if (type === 'punch')    return { label: 'Punch',    color: '#E63946', emoji: '🥊' }
  if (type === 'defense')  return { label: 'Defense',  color: '#42a5f5', emoji: '🛡️' }
  if (type === 'strength') return { label: 'Strength', color: '#c084fc', emoji: '💪' }
  return                          { label: 'Training', color: '#888888', emoji: '⭐' }
}
